services:
  - type: worker
    name: discord-voice-logger
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python Botdiscord.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
